/**
 * Country lookup table.
 *
 * Records are derived from UN M49 and ISO 3166-1. `aliases` holds additional lowercase
 * forms — historical names (Burma, Persia, Ceylon), common alternates (Ivory
 * Coast, Czech Republic), and native-language variants — that resolve to the
 * record's iso3 alongside the canonical `name`. Input is trimmed and lowercased
 * before lookup, then matched exactly against the alias index; partial / fuzzy
 * matching is not supported.
 *
 * The aliases below have been deliberately canonicalized: Latin and Arabic
 * diacritics are stripped, apostrophes / periods / parens / commas removed,
 * hyphens replaced with spaces, and `st` expanded to `saint`. This is
 * intentional — `lookupAlpha3` applies the same `sanitize` transform to user
 * input at lookup time, so accented / punctuated forms (e.g. "Côte d'Ivoire",
 * "U.K.", "Guinea-Bissau", "St. Kitts") still resolve. Storing the canonical
 * form keeps the alias list smaller and avoids redundant variants. Don't add
 * accented or punctuated variants by hand.
 *
 * Aliases within each record are sorted with `Intl.Collator("en")` so emoji come first, then
 * Latin (with `æ` / `ø` interleaved next to ASCII), then non-Latin scripts.
 *
 * To add custom records (private codes for sub-national regions, historical
 * countries, disputed areas, etc.), don't edit this file — pass your own
 * records to `createLookup` from `./index` and use the returned scoped helpers.
 */

export interface CountryRecord {
    /** ISO 3166-1 alpha-3 code; canonical id returned by `lookupAlpha3`. */
    readonly iso3: string;
    /** ISO 3166-1 alpha-2 code. */
    readonly iso2: string;
    /** UN M49 numeric code, 3-digit zero-padded string (e.g. "004" for Afghanistan). */
    readonly m49: string;
    /** English short name as it appears in the UN M49. */
    readonly name: string;
    /**
     * Additional lowercase forms (excluding the canonical `name`) that resolve
     * to this record's iso3. Input is trimmed and lowercased before testing,
     * so aliases must already be lowercased.
     */
    readonly aliases: readonly string[];
}

export const COUNTRIES: ReadonlyArray<CountryRecord> = [
    {
        iso3: "ABW",
        iso2: "AW",
        m49: "533",
        name: "Aruba",
        aliases: ["🇦🇼", "country of aruba", "land aruba", "pais aruba"],
    },
    {
        iso3: "AFG",
        iso2: "AF",
        m49: "004",
        name: "Afghanistan",
        aliases: [
            "🇦🇫",
            "affghanistan",
            "affghanisthan",
            "affghaunistan",
            "afghania",
            "afghanisthan",
            "afghaunistan",
            "afghaunistaun",
            "afgoniston",
            "de afghanistan islami jumhuriyat",
            "owganystan",
            "афғонистон",
            "أفغانستان",
            "افغانستان",
            "د افغانستان اسلامی جمهوریت",
        ],
    },
    {
        iso3: "AGO",
        iso2: "AO",
        m49: "024",
        name: "Angola",
        aliases: ["🇦🇴", "republic of angola", "republica de angola"],
    },
    {
        iso3: "AIA",
        iso2: "AI",
        m49: "660",
        name: "Anguilla",
        aliases: ["🇦🇮", "malliouhana"],
    },
    {
        iso3: "ALA",
        iso2: "AX",
        m49: "248",
        name: "Åland Islands",
        aliases: [
            "🇦🇽",
            "aaland",
            "aaland islands",
            "ahvenanmaa",
            "aland",
            "aland isles",
            "aland region",
            "alands lan",
            "landskapet aland",
        ],
    },
    {
        iso3: "ALB",
        iso2: "AL",
        m49: "008",
        name: "Albania",
        aliases: [
            "🇦🇱",
            "peoples republic of albania",
            "peoples socialist republic of albania",
            "republic of albania",
            "republika e shqiperise",
            "shqiperi",
            "shqiperia",
            "shqiperise",
            "socialist republic of albania",
        ],
    },
    {
        iso3: "AND",
        iso2: "AD",
        m49: "020",
        name: "Andorra",
        aliases: [
            "🇦🇩",
            "el pais dels pirineus",
            "les valls dandorra",
            "principality of andorra",
            "principality of the valleys of andorra",
            "principat dandorra",
            "valls dandorra",
        ],
    },
    {
        iso3: "ARE",
        iso2: "AE",
        m49: "784",
        name: "United Arab Emirates",
        aliases: [
            "🇦🇪",
            "emirates",
            "the uae",
            "الإمارات",
            "الإمارات العربية المتحدة",
            "الامارات",
            "الامارات العربية المتحدة",
            "دولة الإمارات العربية المتحدة",
        ],
    },
    {
        iso3: "ARG",
        iso2: "AR",
        m49: "032",
        name: "Argentina",
        aliases: ["🇦🇷", "argentine republic", "nacion argentina", "republic of argentina", "republica argentina"],
    },
    {
        iso3: "ARM",
        iso2: "AM",
        m49: "051",
        name: "Armenia",
        aliases: [
            "🇦🇲",
            "hayastan",
            "hayastani hanrapetutyun",
            "republic of armenia",
            "հայաստան",
            "հայաստանի հանրապետություն",
            "հայք",
            "հհ",
        ],
    },
    {
        iso3: "ASM",
        iso2: "AS",
        m49: "016",
        name: "American Samoa",
        aliases: [
            "🇦🇸",
            "amerika samoa",
            "east samoa",
            "samoa american",
            "samoa united states",
            "territory of american samoa",
            "us samoa",
        ],
    },
    {
        iso3: "ATA",
        iso2: "AQ",
        m49: "010",
        name: "Antarctica",
        aliases: ["🇦🇶", "antarctica treaty area"],
    },
    {
        iso3: "ATF",
        iso2: "TF",
        m49: "260",
        name: "French Southern Territories",
        aliases: [
            "🇹🇫",
            "taaf",
            "terres australes et antarctiques francaises",
            "terres australes francaises",
            "terres australes francaises les",
            "territoire des terres australes et antarctiques francaises",
        ],
    },
    {
        iso3: "ATG",
        iso2: "AG",
        m49: "028",
        name: "Antigua and Barbuda",
        aliases: ["🇦🇬", "antigua barbuda"],
    },
    {
        iso3: "AUS",
        iso2: "AU",
        m49: "036",
        name: "Australia",
        aliases: ["🇦🇺", "commonwealth of australia", "new holland", "new hollandia", "nova hollandia"],
    },
    {
        iso3: "AUT",
        iso2: "AT",
        m49: "040",
        name: "Austria",
        aliases: ["🇦🇹", "osterreich", "republic of austria", "republik osterreich", "zweite republik"],
    },
    {
        iso3: "AZE",
        iso2: "AZ",
        m49: "031",
        name: "Azerbaijan",
        aliases: ["🇦🇿", "azərbaycan", "azərbaycan respublikası", "republic of azerbaijan"],
    },
    {
        iso3: "BDI",
        iso2: "BI",
        m49: "108",
        name: "Burundi",
        aliases: [
            "🇧🇮",
            "gouvernement du burundi",
            "la republique du burundi",
            "republic of burundi",
            "republika yu burundi",
            "republika yuburundi",
            "republique du burundi",
            "repuburika yuburundi",
            "uburundi",
        ],
    },
    {
        iso3: "BEL",
        iso2: "BE",
        m49: "056",
        name: "Belgium",
        aliases: [
            "🇧🇪",
            "belg",
            "belgie",
            "belgien",
            "belgique",
            "kingdom of belgium",
            "konigreich belgien",
            "koninkrijk belgie",
            "royaume de belgique",
        ],
    },
    {
        iso3: "BEN",
        iso2: "BJ",
        m49: "204",
        name: "Benin",
        aliases: ["🇧🇯", "dahomey", "la republique du benin", "republic of benin", "republique du benin"],
    },
    {
        iso3: "BES",
        iso2: "BQ",
        m49: "535",
        name: "Bonaire, Sint Eustatius and Saba",
        aliases: [
            "🇧🇶",
            "bes eilanden",
            "bes islands",
            "bijzondere gemeente",
            "bonaire saint eustatius and saba",
            "bonaire sint eustatius en saba",
            "caraibisch nederland",
            "caribbean netherlands",
            "caribisch nederland",
            "hulanda karibense",
            "islanan bes",
            "netherlands antilles",
        ],
    },
    {
        iso3: "BFA",
        iso2: "BF",
        m49: "854",
        name: "Burkina Faso",
        aliases: ["🇧🇫", "republic of burkina faso", "republic of upper volta"],
    },
    {
        iso3: "BGD",
        iso2: "BD",
        m49: "050",
        name: "Bangladesh",
        aliases: [
            "🇧🇩",
            "bangla desh",
            "gonaoprojatontri bangladesh",
            "peoples republic of bangladesh",
            "গণপ্রজাতন্ত্রী বাংলাদেশ",
            "বাংলা দেশ",
            "বাংলাদেশ",
            "বিডি",
        ],
    },
    {
        iso3: "BGR",
        iso2: "BG",
        m49: "100",
        name: "Bulgaria",
        aliases: [
            "🇧🇬",
            "bulgarian republic",
            "republic of bulgaria",
            "republika bulgaria",
            "republika bulgariya",
            "бг",
            "българия",
            "република българия",
        ],
    },
    {
        iso3: "BHR",
        iso2: "BH",
        m49: "048",
        name: "Bahrain",
        aliases: ["🇧🇭", "bahrein islands", "kingdom of bahrain", "البحرين", "دولة البحرين", "مملكة البحرين"],
    },
    {
        iso3: "BHS",
        iso2: "BS",
        m49: "044",
        name: "Bahamas",
        aliases: ["🇧🇸", "bahama islands", "bahamas the", "commonwealth of the bahamas"],
    },
    {
        iso3: "BIH",
        iso2: "BA",
        m49: "070",
        name: "Bosnia and Herzegovina",
        aliases: [
            "🇧🇦",
            "bosna",
            "bosna i hercegovina",
            "bosnia",
            "bosnia and hercegovina",
            "bosnia herzegovina",
            "бих",
            "босна",
            "босна и херцеговина",
            "бх",
        ],
    },
    {
        iso3: "BLM",
        iso2: "BL",
        m49: "652",
        name: "Saint Barthélemy",
        aliases: [
            "🇧🇱",
            "collectivite doutre mer de saint barthelemy",
            "collectivite territoriale de saint barthelemy",
            "collectivity of saint barthelemy",
            "saint barth",
            "saint barths",
            "saint barts",
            "saint bartz",
        ],
    },
    {
        iso3: "BLR",
        iso2: "BY",
        m49: "112",
        name: "Belarus",
        aliases: [
            "🇧🇾",
            "republic of belarus",
            "respublika belarus",
            "respublika byelarus",
            "беларуская рэспубліка",
            "беларусь",
            "белая русь",
            "белоруссия",
            "рб",
            "республика беларусь",
            "рэспубліка беларусь",
        ],
    },
    {
        iso3: "BLZ",
        iso2: "BZ",
        m49: "084",
        name: "Belize",
        aliases: ["🇧🇿"],
    },
    {
        iso3: "BMU",
        iso2: "BM",
        m49: "060",
        name: "Bermuda",
        aliases: [
            "🇧🇲",
            "barmuda",
            "barmuda i",
            "barmuda isl",
            "barmuda islands",
            "barmudas",
            "bermoothes",
            "bermuda islands",
            "bermudas",
            "bermudian islands",
            "colony of bermuda",
            "devils isles",
            "isle of devils",
            "somers islands",
            "somers isles",
            "summers isles",
            "territory of bermuda",
            "virgineola",
        ],
    },
    {
        iso3: "BOL",
        iso2: "BO",
        m49: "068",
        name: "Bolivia (Plurinational State of)",
        aliases: [
            "🇧🇴",
            "bolivia",
            "bulibiya",
            "estado plurinacional de bolivia",
            "plurinational state of bolivia",
            "puliwya",
            "republic of bolivia",
            "republica de bolivia",
            "volivia",
            "wuliwiya",
            "wuliwya",
        ],
    },
    {
        iso3: "BRA",
        iso2: "BR",
        m49: "076",
        name: "Brazil",
        aliases: ["🇧🇷", "brasil", "federative republic of brazil", "pindorama", "republica federativa do brasil"],
    },
    {
        iso3: "BRB",
        iso2: "BB",
        m49: "052",
        name: "Barbados",
        aliases: ["🇧🇧", "barbadoes"],
    },
    {
        iso3: "BRN",
        iso2: "BN",
        m49: "096",
        name: "Brunei Darussalam",
        aliases: ["🇧🇳", "brunei", "nation of brunei the abode of peace", "negara brunei darussalam"],
    },
    {
        iso3: "BTN",
        iso2: "BT",
        m49: "064",
        name: "Bhutan",
        aliases: ["🇧🇹", "kingdom of bhutan", "འབྲུག", "འབྲུག་ཡུལ་", "འབྲུགཡུལ་་"],
    },
    {
        iso3: "BVT",
        iso2: "BV",
        m49: "074",
        name: "Bouvet Island",
        aliases: ["🇧🇻"],
    },
    {
        iso3: "BWA",
        iso2: "BW",
        m49: "072",
        name: "Botswana",
        aliases: ["🇧🇼", "lefatshe la botswana", "republic of botswana"],
    },
    {
        iso3: "CAF",
        iso2: "CF",
        m49: "140",
        name: "Central African Republic",
        aliases: [
            "🇨🇫",
            "centrafricaine republique",
            "centrafrique",
            "central africa",
            "kodorosese ti beafrika",
            "la republique",
            "rep centrafrique",
            "republique centrafricaine",
        ],
    },
    {
        iso3: "CAN",
        iso2: "CA",
        m49: "124",
        name: "Canada",
        aliases: ["🇨🇦", "le canada"],
    },
    {
        iso3: "CCK",
        iso2: "CC",
        m49: "166",
        name: "Cocos (Keeling) Islands",
        aliases: ["🇨🇨", "cocos islands", "keeling islands", "territory of the cocos keeling islands"],
    },
    {
        iso3: "CHE",
        iso2: "CH",
        m49: "756",
        name: "Switzerland",
        aliases: [
            "🇨🇭",
            "confederation helvetique",
            "confederation suisse",
            "confederazione elvetica",
            "confederazione svizzera",
            "confederaziun svizra",
            "confoederatio helvetica",
            "confœderatio helvetica",
            "eidgenossenschaft",
            "elvezia",
            "helvetie",
            "la confederation suisse",
            "schweiz",
            "schweizerische eidgenossenschaft",
            "suisse",
            "svizra",
            "svizzera",
            "swiss",
            "swiss confederation",
        ],
    },
    {
        iso3: "CHL",
        iso2: "CL",
        m49: "152",
        name: "Chile",
        aliases: ["🇨🇱", "republic of chile", "republica de chile"],
    },
    {
        iso3: "CHN",
        iso2: "CN",
        m49: "156",
        name: "China",
        aliases: ["🇨🇳", "china pr", "pr china", "prc", "the peoples republic of china", "中华人民共和国", "中国"],
    },
    {
        iso3: "CIV",
        iso2: "CI",
        m49: "384",
        name: "Côte d'Ivoire",
        aliases: [
            "🇨🇮",
            "cote ivoire",
            "ivory coast",
            "republic of cote divoire",
            "republic of ivory coast",
            "republic of the ivory coast",
            "republique de cote divoire",
        ],
    },
    {
        iso3: "CMR",
        iso2: "CM",
        m49: "120",
        name: "Cameroon",
        aliases: ["🇨🇲", "cameroun", "la republique du cameroun", "republic of cameroon", "republique du cameroun"],
    },
    {
        iso3: "COD",
        iso2: "CD",
        m49: "180",
        name: "Democratic Republic of the Congo",
        aliases: [
            "🇨🇩",
            "congo belge",
            "congo kinshasa",
            "dem rep congo",
            "dem republic of congo",
            "dem republic of the congo",
            "democratic republic of congo",
            "dr congo",
            "rd congo",
            "rep demcongo",
            "republic of the congo",
            "republique democratique du congo",
            "republique du zaire",
            "zaire",
        ],
    },
    {
        iso3: "COG",
        iso2: "CG",
        m49: "178",
        name: "Congo",
        aliases: [
            "🇨🇬",
            "congo brazza",
            "congo brazzaville",
            "congo republic",
            "rep congo",
            "republic of congo",
            "republique du congo",
        ],
    },
    {
        iso3: "COK",
        iso2: "CK",
        m49: "184",
        name: "Cook Islands",
        aliases: ["🇨🇰", "cook group", "hervey islands"],
    },
    {
        iso3: "COL",
        iso2: "CO",
        m49: "170",
        name: "Colombia",
        aliases: ["🇨🇴", "republic of colombia", "republica de colombia"],
    },
    {
        iso3: "COM",
        iso2: "KM",
        m49: "174",
        name: "Comoros",
        aliases: [
            "🇰🇲",
            "comores",
            "comores archipel",
            "etat comorien",
            "lunion des comores",
            "republique des comores",
            "republique federale et islamique des comores",
            "republique federale islamique des comores",
            "territoire des comores",
            "union des comores",
            "union of the comoros",
            "إتحاد القمر",
            "اتحاد جزر القمر",
            "الاتحاد القمري",
            "القمر",
            "جزر القمر",
            "جمهورية القمر المتحدة",
            "جمهورية جزر القمر الاتحادية الإسلامية",
            "جمهورية جزرالقمر المتحدة",
        ],
    },
    {
        iso3: "CPV",
        iso2: "CV",
        m49: "132",
        name: "Cabo Verde",
        aliases: [
            "🇨🇻",
            "cape verde",
            "cape verde islands",
            "kab verd",
            "kabu verdi",
            "kauberdi",
            "republic of cabo verde",
            "republic of cape verde",
            "republica de cabo verde",
        ],
    },
    {
        iso3: "CRI",
        iso2: "CR",
        m49: "188",
        name: "Costa Rica",
        aliases: ["🇨🇷", "republic of costa rica", "republica de costa rica"],
    },
    {
        iso3: "CUB",
        iso2: "CU",
        m49: "192",
        name: "Cuba",
        aliases: ["🇨🇺", "isla juana", "republic of cuba", "republica de cuba"],
    },
    {
        iso3: "CUW",
        iso2: "CW",
        m49: "531",
        name: "Curaçao",
        aliases: [
            "🇨🇼",
            "corsou",
            "corsouw",
            "corsow",
            "country of curacao",
            "curacau",
            "curacoa",
            "curazao",
            "curaςao",
            "curocao",
            "island territory of curacao",
            "korsou",
            "land curacao",
            "pais korsou",
        ],
    },
    {
        iso3: "CXR",
        iso2: "CX",
        m49: "162",
        name: "Christmas Island",
        aliases: [
            "🇨🇽",
            "christmas island other territories",
            "christmas island other territories australia",
            "territory of christmas island",
        ],
    },
    {
        iso3: "CYM",
        iso2: "KY",
        m49: "136",
        name: "Cayman Islands",
        aliases: ["🇰🇾", "caymans"],
    },
    {
        iso3: "CYP",
        iso2: "CY",
        m49: "196",
        name: "Cyprus",
        aliases: [
            "🇨🇾",
            "greek administration of southern cyprus",
            "greek cypriot state",
            "guney kıbrıs",
            "guney kıbrıs rum cumhuriyeti",
            "guney kıbrıs rum kesimi",
            "guney kıbrıs rum yonetimi",
            "kipriaki dhimokratia",
            "kıbrıs",
            "kıbrıs cumhuriyeti",
            "kıbrıs rum kesimi",
            "kypriaki dimokratia",
            "kypros",
            "republic of cyprus",
            "κυπριακη δημοκρατια",
            "κυπρος",
        ],
    },
    {
        iso3: "CZE",
        iso2: "CZ",
        m49: "203",
        name: "Czechia",
        aliases: ["🇨🇿", "ceska republika", "ceske kraje", "ceske uzemi", "ceske zeme", "cesko", "cr", "czech republic"],
    },
    {
        iso3: "DEU",
        iso2: "DE",
        m49: "276",
        name: "Germany",
        aliases: [
            "🇩🇪",
            "br deutschland",
            "bundesrepublik",
            "bundesrepublik deutschland",
            "deutschland",
            "federal republic of germany",
        ],
    },
    {
        iso3: "DJI",
        iso2: "DJ",
        m49: "262",
        name: "Djibouti",
        aliases: [
            "🇩🇯",
            "la republique de djibouti",
            "republic of djibouti",
            "republique de djibouti",
            "جمهورية جيبوتي",
            "جيبوتي",
        ],
    },
    {
        iso3: "DMA",
        iso2: "DM",
        m49: "212",
        name: "Dominica",
        aliases: ["🇩🇲", "commonwealth of dominica", "island of dominica", "waitu kubuli"],
    },
    {
        iso3: "DNK",
        iso2: "DK",
        m49: "208",
        name: "Denmark",
        aliases: ["🇩🇰", "dania", "danmark", "denmark proper", "kongeriget danmark", "metropolitan denmark"],
    },
    {
        iso3: "DOM",
        iso2: "DO",
        m49: "214",
        name: "Dominican Republic",
        aliases: [
            "🇩🇴",
            "dominicana",
            "domrep",
            "haiti espanol",
            "quisqueya",
            "republica de santo domingo",
            "republica dominicana",
            "santo domingo",
        ],
    },
    {
        iso3: "DZA",
        iso2: "DZ",
        m49: "012",
        name: "Algeria",
        aliases: [
            "🇩🇿",
            "peoples democratic republic of algeria",
            "الجزائر",
            "الجزاير",
            "الجمهورية الجزائرية الديمقراطية الشعبية",
            "الدزاير",
            "دزاير",
        ],
    },
    {
        iso3: "ECU",
        iso2: "EC",
        m49: "218",
        name: "Ecuador",
        aliases: [
            "🇪🇨",
            "el ecuador",
            "estado ecuatoriano",
            "republic of ecuador",
            "republic of equator",
            "republic of the equator",
            "republica del ecuador",
            "the ecuadorian state",
        ],
    },
    {
        iso3: "EGY",
        iso2: "EG",
        m49: "818",
        name: "Egypt",
        aliases: [
            "🇪🇬",
            "arab rep egypt",
            "arab republic of egypt",
            "rep egypt",
            "republic of egypt",
            "جمهورية مصر العربية",
            "مصر",
        ],
    },
    {
        iso3: "ERI",
        iso2: "ER",
        m49: "232",
        name: "Eritrea",
        aliases: [
            "🇪🇷",
            "ertra",
            "hagere ertra",
            "hagere iertra",
            "iertra",
            "iritriya",
            "state of eritrea",
            "إرتريا",
            "إريتريا",
            "ارتريا",
            "ارتيريا",
            "اريتريا",
            "دولة إرتريا",
            "دولة إريتريا",
            "ሃገረ ኤርትራ",
            "ኤርትራ",
        ],
    },
    {
        iso3: "ESH",
        iso2: "EH",
        m49: "732",
        name: "Western Sahara",
        aliases: ["🇪🇭", "southern provinces", "spanish sahara", "west sahara"],
    },
    {
        iso3: "ESP",
        iso2: "ES",
        m49: "724",
        name: "Spain",
        aliases: ["🇪🇸", "espana", "estado espanol", "kingdom of spain", "reino de espana"],
    },
    {
        iso3: "EST",
        iso2: "EE",
        m49: "233",
        name: "Estonia",
        aliases: [
            "🇪🇪",
            "eesti",
            "eesti noukogude sotsialistlik vabariik",
            "eesti vabariik",
            "estland",
            "republic of estonia",
        ],
    },
    {
        iso3: "ETH",
        iso2: "ET",
        m49: "231",
        name: "Ethiopia",
        aliases: [
            "🇪🇹",
            "federal democratic republic of ethiopia",
            "ityopiya",
            "yeityopiya federalawi demokrasiyawi ripeblik",
            "yeityopiya hizbawi dimokrasiyawi ripublik",
            "ኢትዮጵያ",
            "የኢትዮጵያ ፌዴራላዊ ዴሞክራሲያዊ ሪፐብሊክ",
        ],
    },
    {
        iso3: "FIN",
        iso2: "FI",
        m49: "246",
        name: "Finland",
        aliases: ["🇫🇮", "republic of finland", "republiken finland", "suomen tasavalta", "suomi"],
    },
    {
        iso3: "FJI",
        iso2: "FJ",
        m49: "242",
        name: "Fiji",
        aliases: [
            "🇫🇯",
            "fiji ganarajya",
            "matanitu ko viti",
            "matanitu tugalala o viti",
            "republic of fiji",
            "republic of the fiji islands",
            "viti",
        ],
    },
    {
        iso3: "FLK",
        iso2: "FK",
        m49: "238",
        name: "Falkland Islands (Malvinas)",
        aliases: [
            "🇫🇰",
            "colony of the falkland islands",
            "falkland islands",
            "falklands",
            "islas malvinas",
            "malvinas",
            "malvinas islands",
        ],
    },
    {
        iso3: "FRA",
        iso2: "FR",
        m49: "250",
        name: "France",
        aliases: [
            "🇫🇷",
            "fr",
            "french republic",
            "la france",
            "la republique francaise",
            "lhexagone",
            "republique francaise",
        ],
    },
    {
        iso3: "FRO",
        iso2: "FO",
        m49: "234",
        name: "Faroe Islands",
        aliases: [
            "🇫🇴",
            "faer oer",
            "færø",
            "faeroe is",
            "faeroe islands",
            "faeroe isles",
            "færøerne",
            "faeroes",
            "far oer",
            "faroe island",
            "faroe isles",
            "faroes",
            "faroese islands",
            "føroya",
            "føroyar",
            "føroyum",
        ],
    },
    {
        iso3: "FSM",
        iso2: "FM",
        m49: "583",
        name: "Micronesia (Federated States of)",
        aliases: [
            "🇫🇲",
            "fed sts micronesia",
            "fed sts of micronesia",
            "federated states of micronesia",
            "federated states of micronesia fsm",
            "micronesia",
        ],
    },
    {
        iso3: "GAB",
        iso2: "GA",
        m49: "266",
        name: "Gabon",
        aliases: [
            "🇬🇦",
            "gabonese republic",
            "la republique gabonaise",
            "le gabon",
            "republique du gabon",
            "republique gabonaise",
        ],
    },
    {
        iso3: "GBR",
        iso2: "GB",
        m49: "826",
        name: "United Kingdom of Great Britain and Northern Ireland",
        aliases: [
            "🇬🇧",
            "britain",
            "england",
            "great britain",
            "great britain and northern ireland",
            "northern ireland",
            "scotland",
            "the uk",
            "the united kingdom",
            "wales",
        ],
    },
    {
        iso3: "GEO",
        iso2: "GE",
        m49: "268",
        name: "Georgia",
        aliases: [
            "🇬🇪",
            "georgia country",
            "republic of georgia",
            "sakartvelo",
            "қырҭтәыла",
            "საქართველო",
            "საქართველოს რესპუბლიკა",
        ],
    },
    {
        iso3: "GGY",
        iso2: "GG",
        m49: "831",
        name: "Guernsey",
        aliases: [
            "🇬🇬",
            "bailiwick of guernsey",
            "bailliage de guernesey",
            "bailliage de guernesi",
            "giernesi",
            "great britain guernsey",
            "guernesey",
            "lisia",
        ],
    },
    {
        iso3: "GHA",
        iso2: "GH",
        m49: "288",
        name: "Ghana",
        aliases: ["🇬🇭", "republic of ghana"],
    },
    {
        iso3: "GIB",
        iso2: "GI",
        m49: "292",
        name: "Gibraltar",
        aliases: ["🇬🇮", "the rock of gibraltar"],
    },
    {
        iso3: "GIN",
        iso2: "GN",
        m49: "324",
        name: "Guinea",
        aliases: ["🇬🇳", "guinee", "guinee conakry", "republic of guinea", "republique de guinee"],
    },
    {
        iso3: "GLP",
        iso2: "GP",
        m49: "312",
        name: "Guadeloupe",
        aliases: ["🇬🇵"],
    },
    {
        iso3: "GMB",
        iso2: "GM",
        m49: "270",
        name: "Gambia",
        aliases: ["🇬🇲", "islamic republic of the gambia", "republic of the gambia"],
    },
    {
        iso3: "GNB",
        iso2: "GW",
        m49: "624",
        name: "Guinea-Bissau",
        aliases: ["🇬🇼", "guine bissau", "republic of guinea bissau", "republica da guine bissau"],
    },
    {
        iso3: "GNQ",
        iso2: "GQ",
        m49: "226",
        name: "Equatorial Guinea",
        aliases: [
            "🇬🇶",
            "guine equatorial",
            "guinea ecuatorial",
            "guinea espanola",
            "guinee equat",
            "guinee equatoriale",
            "la republique de guinee equatoriale",
            "posesiones espanolas del golfo de guinea",
            "provincia de la guinea ecuatorial",
            "republic of equatorial guinea",
            "republica da guine equatorial",
            "republica de guinea ecuatorial",
            "territorios espanoles del golfo de guinea",
        ],
    },
    {
        iso3: "GRC",
        iso2: "GR",
        m49: "300",
        name: "Greece",
        aliases: [
            "🇬🇷",
            "ellada",
            "ellas",
            "elliniki dhimokratia",
            "elliniki dimokratia",
            "greek republic",
            "hellas",
            "hellas greece",
            "hellenic republic",
            "vasilion tis ellados",
            "δημοκρατια της ελλαδας",
            "δημοκρατια της ελλαδος",
            "ελλαδα",
            "ελλας",
            "ελλας ελλαδα",
            "ελληνικη δημοκρατια",
        ],
    },
    {
        iso3: "GRD",
        iso2: "GD",
        m49: "308",
        name: "Grenada",
        aliases: ["🇬🇩"],
    },
    {
        iso3: "GRL",
        iso2: "GL",
        m49: "304",
        name: "Greenland",
        aliases: ["🇬🇱", "kalaallit nunaat"],
    },
    {
        iso3: "GTM",
        iso2: "GT",
        m49: "320",
        name: "Guatemala",
        aliases: ["🇬🇹", "republic of guatemala", "republica de guatemala"],
    },
    {
        iso3: "GUF",
        iso2: "GF",
        m49: "254",
        name: "French Guiana",
        aliases: [
            "🇬🇫",
            "fr 973",
            "guiana",
            "guiana france",
            "guyane",
            "guyane francaise",
            "gwiyann",
            "gwiyann franse",
            "lagwiyann",
        ],
    },
    {
        iso3: "GUM",
        iso2: "GU",
        m49: "316",
        name: "Guam",
        aliases: ["🇬🇺", "guahan", "guam usa", "islan guahan", "island of guam", "territory of guam"],
    },
    {
        iso3: "GUY",
        iso2: "GY",
        m49: "328",
        name: "Guyana",
        aliases: ["🇬🇾", "co operative republic of guyana", "republic of guyana"],
    },
    {
        iso3: "HKG",
        iso2: "HK",
        m49: "344",
        name: "Hong Kong",
        aliases: [
            "🇭🇰",
            "hksar",
            "hong kong sar",
            "hong kong special administrative region",
            "hong kong special administrative region of the peoples republic of china",
            "hongkong",
        ],
    },
    {
        iso3: "HMD",
        iso2: "HM",
        m49: "334",
        name: "Heard Island and McDonald Islands",
        aliases: [
            "🇭🇲",
            "heard & mcdonald islands",
            "heard and macdonald islands",
            "himi",
            "territory of heard island and mcdonald islands",
        ],
    },
    {
        iso3: "HND",
        iso2: "HN",
        m49: "340",
        name: "Honduras",
        aliases: ["🇭🇳", "guaymuras", "higueras", "honduran republic", "republic of honduras", "republica de honduras"],
    },
    {
        iso3: "HRV",
        iso2: "HR",
        m49: "191",
        name: "Croatia",
        aliases: ["🇭🇷", "hrvatska", "republic of croatia", "republika hrvatska"],
    },
    {
        iso3: "HTI",
        iso2: "HT",
        m49: "332",
        name: "Haiti",
        aliases: [
            "🇭🇹",
            "ayiti",
            "haitian republic",
            "la republique dhaiti",
            "repiblik d ayiti",
            "republic of haiti",
            "republique dhaiti",
        ],
    },
    {
        iso3: "HUN",
        iso2: "HU",
        m49: "348",
        name: "Hungary",
        aliases: [
            "🇭🇺",
            "a magyar koztarsasag",
            "a magyar nepkoztarsasag",
            "harmadik magyar koztarsasag",
            "magyar koztarsasag",
            "magyar nepkoztarsasag",
            "magyarorszag",
            "mo",
        ],
    },
    {
        iso3: "IDN",
        iso2: "ID",
        m49: "360",
        name: "Indonesia",
        aliases: ["🇮🇩", "negara kesatuan republik indonesia", "nkri", "republic of indonesia", "republik indonesia"],
    },
    {
        iso3: "IMN",
        iso2: "IM",
        m49: "833",
        name: "Isle of Man",
        aliases: ["🇮🇲", "ellan vannin", "i man", "i mann", "i mannin", "isle of mann", "mann", "mannin", "manx"],
    },
    {
        iso3: "IND",
        iso2: "IN",
        m49: "356",
        name: "India",
        aliases: [
            "🇮🇳",
            "al hind",
            "bharat",
            "bharat ganarajya",
            "bharata",
            "bharatvarsh",
            "hindoostan",
            "hindustan",
            "indostan",
            "republic of india",
            "tenjiku",
            "tianzhu",
            "आर्यवर्त",
            "इंडिया",
            "इण्डिया",
            "भारत",
            "भारत गणराज्य",
            "भारतवर्ष",
            "हिंदुस्तान",
            "हिन्दुस्तान",
            "हिन्दोस्तान",
        ],
    },
    {
        iso3: "IOT",
        iso2: "IO",
        m49: "086",
        name: "British Indian Ocean Territory",
        aliases: ["🇮🇴", "biot"],
    },
    {
        iso3: "IRL",
        iso2: "IE",
        m49: "372",
        name: "Ireland",
        aliases: [
            "🇮🇪",
            "eire",
            "hibernia",
            "irish republic",
            "poblacht na heireann",
            "republic of ireland",
            "southern ireland",
        ],
    },
    {
        iso3: "IRN",
        iso2: "IR",
        m49: "364",
        name: "Iran (Islamic Republic of)",
        aliases: [
            "🇮🇷",
            "iran",
            "islamic rep iran",
            "islamic republic of iran",
            "persia",
            "ایران",
            "ایرانزمین",
            "پارس",
            "جمهوری اسلامی ايران",
            "جمهوری اسلامی ایران",
            "كشور شاهنشاهی ايران",
        ],
    },
    {
        iso3: "IRQ",
        iso2: "IQ",
        m49: "368",
        name: "Iraq",
        aliases: [
            "🇮🇶",
            "eraq",
            "iraqe",
            "komar i eraq",
            "republic of iraq",
            "الجمهورية العراقية",
            "العراق",
            "جمهورية العراق",
            "عراق",
            "عێراق",
        ],
    },
    {
        iso3: "ISL",
        iso2: "IS",
        m49: "352",
        name: "Iceland",
        aliases: ["🇮🇸", "icelandic republic", "island", "lyðveldið island", "republic of iceland", "ysland"],
    },
    {
        iso3: "ISR",
        iso2: "IL",
        m49: "376",
        name: "Israel",
        aliases: ["🇮🇱", "erez yisrael", "medinat yisrael", "state of israel", "yisrael", "ישראל", "מדינת ישראל"],
    },
    {
        iso3: "ITA",
        iso2: "IT",
        m49: "380",
        name: "Italy",
        aliases: ["🇮🇹", "il bel paese", "italia", "italian republic", "repubblica italiana", "republic of italy"],
    },
    {
        iso3: "JAM",
        iso2: "JM",
        m49: "388",
        name: "Jamaica",
        aliases: ["🇯🇲", "commonwealth of jamaica", "jamieka", "jomieka", "jumieka"],
    },
    {
        iso3: "JEY",
        iso2: "JE",
        m49: "832",
        name: "Jersey",
        aliases: [
            "🇯🇪",
            "bailliage de jerri",
            "bailliage de jersey",
            "balliwick of jersey",
            "i iersey",
            "i jersey",
            "iersey",
            "iersey i",
            "isle of jersey",
            "jerri",
            "jersey i",
            "jersey island",
        ],
    },
    {
        iso3: "JOR",
        iso2: "JO",
        m49: "400",
        name: "Jordan",
        aliases: [
            "🇯🇴",
            "giordania",
            "hashemite kingdom of jordan",
            "kingdom of jordan",
            "state of jordan",
            "yarden",
            "الأردن",
            "الاردن",
            "المملكة الأردنية الهاشمية",
            "المملكة الاردنية الهاشمية",
        ],
    },
    {
        iso3: "JPN",
        iso2: "JP",
        m49: "392",
        name: "Japan",
        aliases: [
            "🇯🇵",
            "state of japan",
            "あきつしま",
            "おおやしま",
            "しきしま",
            "ジャパン",
            "しんしゅう",
            "にっぽん",
            "にっぽんこく",
            "にほん",
            "にほんこく",
            "ひいずるくに",
            "ふそう",
            "大八州",
            "扶木之地",
            "扶桑",
            "扶桑国",
            "敷島",
            "日出る国",
            "日本",
            "榑木之地",
            "瑞穂国",
            "神州",
            "秋津島",
            "葦原中国",
        ],
    },
    {
        iso3: "KAZ",
        iso2: "KZ",
        m49: "398",
        name: "Kazakhstan",
        aliases: [
            "🇰🇿",
            "qazaqstan",
            "qazaqstan respublikasy",
            "republic of kazakhstan",
            "казахстан",
            "қазақстан",
            "қазақстан республикасы",
            "республика казахстан",
            "рк",
        ],
    },
    {
        iso3: "KEN",
        iso2: "KE",
        m49: "404",
        name: "Kenya",
        aliases: ["🇰🇪", "jamhuri ya kenya", "republic of kenya"],
    },
    {
        iso3: "KGZ",
        iso2: "KG",
        m49: "417",
        name: "Kyrgyzstan",
        aliases: [
            "🇰🇬",
            "kyrgyz republic",
            "kyrgyz respublikasy",
            "kyrgyzstan respublikasy",
            "кр",
            "кыргыз республикасы",
            "кыргызстан",
        ],
    },
    {
        iso3: "KHM",
        iso2: "KH",
        m49: "116",
        name: "Cambodia",
        aliases: [
            "🇰🇭",
            "camboya",
            "campuchia",
            "kambodzha",
            "kamboja",
            "kampuchea",
            "kingdom of cambodia",
            "កម្ពុជា",
            "ព្រះរាជាណាចក្រកម្ពុជា",
        ],
    },
    {
        iso3: "KIR",
        iso2: "KI",
        m49: "296",
        name: "Kiribati",
        aliases: ["🇰🇮", "republic of kiribati"],
    },
    {
        iso3: "KNA",
        iso2: "KN",
        m49: "659",
        name: "Saint Kitts and Nevis",
        aliases: [
            "🇰🇳",
            "federation of saint christopher and nevis",
            "federation of saint kitts and nevis",
            "kitts & nevis",
            "saint christopher and nevis",
        ],
    },
    {
        iso3: "KOR",
        iso2: "KR",
        m49: "410",
        name: "Republic of Korea",
        aliases: [
            "🇰🇷",
            "korea",
            "korea republic",
            "korea south",
            "rep korea",
            "s korea",
            "south korea",
            "taehan minguk",
            "남조선",
            "남한",
            "대한",
            "대한민국",
            "코리아",
            "한국",
        ],
    },
    {
        iso3: "KWT",
        iso2: "KW",
        m49: "414",
        name: "Kuwait",
        aliases: ["🇰🇼", "state of kuwait", "الكويت", "دولة الكويت"],
    },
    {
        iso3: "LAO",
        iso2: "LA",
        m49: "418",
        name: "Lao People's Democratic Republic",
        aliases: [
            "🇱🇦",
            "laos",
            "sathalanalat paxathipatai paxaxon lao",
            "ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ",
            "ປະເທດລາວ",
            "ລາວ",
        ],
    },
    {
        iso3: "LBN",
        iso2: "LB",
        m49: "422",
        name: "Lebanon",
        aliases: ["🇱🇧", "lebanese republic", "republic of lebanon", "state of lebanon", "الجمهورية اللبنانية", "لبنان"],
    },
    {
        iso3: "LBR",
        iso2: "LR",
        m49: "430",
        name: "Liberia",
        aliases: ["🇱🇷", "liber", "republic of liberia"],
    },
    {
        iso3: "LBY",
        iso2: "LY",
        m49: "434",
        name: "Libya",
        aliases: [
            "🇱🇾",
            "state of libya",
            "الجماهيرية العربية الليبية الشعبية الإشتراكية",
            "الجمهورية الليبية",
            "الليبي",
            "الليبية",
            "الليبين",
            "دولة ليبيا",
            "ليببيا",
            "ليبي",
            "ليبيا",
            "ليبية",
        ],
    },
    {
        iso3: "LCA",
        iso2: "LC",
        m49: "662",
        name: "Saint Lucia",
        aliases: ["🇱🇨", "hewanorra", "iyonola"],
    },
    {
        iso3: "LIE",
        iso2: "LI",
        m49: "438",
        name: "Liechtenstein",
        aliases: ["🇱🇮", "furstentum lichtenstein", "furstentum liechtenstein", "principality of liechtenstein"],
    },
    {
        iso3: "LKA",
        iso2: "LK",
        m49: "144",
        name: "Sri Lanka",
        aliases: [
            "🇱🇰",
            "ceylan",
            "ceylon",
            "democratic socialist republic of sri lanka",
            "ilankaic cananayaka cocalicak kutiyarcu",
            "lankava",
            "prajatantravadi samajavadi janarajaya sri lanka",
            "serendib",
            "srilanka",
            "taprobane",
            "இலங்கை",
            "இலங்கை சனநாயக சோசலிசக் குடியரசு",
            "இலங்கை சனநாயக சோஷலிசக் குடியரசு",
            "ஈழம்",
            "சிலோன்",
            "ලංකාව",
            "ශ්රී ලංකා ප්රජාතන්ත්රවාදී සමාජවාදී ජනරජය",
            "ශ්රී ලංකාව",
            "ශ්‍රී ලංකාව",
        ],
    },
    {
        iso3: "LSO",
        iso2: "LS",
        m49: "426",
        name: "Lesotho",
        aliases: ["🇱🇸", "kingdom of lesotho", "mmuso wa lesotho", "the mountain kingdom"],
    },
    {
        iso3: "LTU",
        iso2: "LT",
        m49: "440",
        name: "Lithuania",
        aliases: ["🇱🇹", "lietuva", "lietuvos respublika", "republic of lithuania"],
    },
    {
        iso3: "LUX",
        iso2: "LU",
        m49: "442",
        name: "Luxembourg",
        aliases: [
            "🇱🇺",
            "grand duche",
            "grand duche de luxembourg",
            "grand duchy of luxembourg",
            "großherzogtum luxemburg",
            "groussherzogtum letzebuerg",
            "le grand duche de luxembourg",
            "letzebuerg",
            "letzebuerger land",
            "lux",
            "luxemburg",
        ],
    },
    {
        iso3: "LVA",
        iso2: "LV",
        m49: "428",
        name: "Latvia",
        aliases: [
            "🇱🇻",
            "latveja",
            "latvejas republika",
            "latvian republic",
            "latvija",
            "latvijas republika",
            "letmо",
            "letmо vabamо",
            "republic of latvia",
        ],
    },
    {
        iso3: "MAC",
        iso2: "MO",
        m49: "446",
        name: "Macao",
        aliases: [
            "🇲🇴",
            "aomen",
            "macao sar",
            "macao special administrative region",
            "macao special administrative region of the peoples republic of china",
            "macau",
            "macau rae da china",
            "macau sar",
            "macau special administrative region",
            "macau special administrative region of the peoples republic of china",
            "raem",
            "regiao administrativa especial de macau",
            "regiao administrativa especial de macau da republica popular da china",
            "中國澳門特別行政區",
            "澳門",
        ],
    },
    {
        iso3: "MAF",
        iso2: "MF",
        m49: "663",
        name: "Saint Martin (French Part)",
        aliases: [
            "🇲🇫",
            "collectivite de saint martin",
            "collectivity of saint martin",
            "saint martin",
            "saint martin antilles francaises",
            "saint martin france",
        ],
    },
    {
        iso3: "MAR",
        iso2: "MA",
        m49: "504",
        name: "Morocco",
        aliases: [
            "🇲🇦",
            "kingdom of morocco",
            "المغرب",
            "المملكة المغربية",
            "ⴰⵎⵓⵔ ⵏ ⵡⴰⴽⵓⵛ",
            "ⴰⵎⵕⵕⵓⴽ",
            "ⵍⵎⵕⵕⵓⴽ",
            "ⵍⵎⵖⵔⵉⴱ",
            "ⵜⴰⴳⵍⴷⵉⵜ ⵏ ⵍⵎⵖⵔⵉⴱ",
        ],
    },
    {
        iso3: "MCO",
        iso2: "MC",
        m49: "492",
        name: "Monaco",
        aliases: [
            "🇲🇨",
            "fort hercule",
            "la principaute de monaco",
            "monaco rattachee au district de menton en 1793",
            "munegu",
            "principality and diocese of monaco",
            "principality of monaco",
            "principatu de munegu",
            "principaute de monaco",
        ],
    },
    {
        iso3: "MDA",
        iso2: "MD",
        m49: "498",
        name: "Republic of Moldova",
        aliases: [
            "🇲🇩",
            "moldavia",
            "moldova",
            "moldova republica",
            "r moldova",
            "rep moldova",
            "republica moldova",
            "молдова",
        ],
    },
    {
        iso3: "MDG",
        iso2: "MG",
        m49: "450",
        name: "Madagascar",
        aliases: [
            "🇲🇬",
            "la republique de madagascar",
            "madagasikara",
            "repoblikani madagasikara",
            "republic of madagascar",
            "republique de madagascar",
        ],
    },
    {
        iso3: "MDV",
        iso2: "MV",
        m49: "462",
        name: "Maldives",
        aliases: [
            "🇲🇻",
            "dhivehi raajjeyge jumhooriyyaa",
            "republic of maldives",
            "ދިވެހި ރާއްޖެ",
            "ދިވެހިރާއްޖެ",
            "ދިވެހިރާއްޖޭގެ ޖުމުހޫރިއްޔާ",
            "ދިވެހިރާއްޖޭގެ ޖުމްހޫރިއްޔާ",
        ],
    },
    {
        iso3: "MEX",
        iso2: "MX",
        m49: "484",
        name: "Mexico",
        aliases: [
            "🇲🇽",
            "estados unidos mejicanos",
            "estados unidos mexicanos",
            "mejico",
            "mexican republic",
            "mexican united states",
            "mexihco",
            "mexihko",
            "mexika sentik wexteyowalko",
            "mexiko",
            "mexko",
            "mexko axkayotl",
            "mexko tlalli",
            "nueva espana",
            "republica mejicana",
            "republica mexicana",
            "united mexican states",
            "united states of mexico",
        ],
    },
    {
        iso3: "MHL",
        iso2: "MH",
        m49: "584",
        name: "Marshall Islands",
        aliases: [
            "🇲🇭",
            "aelon kein ad",
            "aolepan aorokin majel",
            "jolet jen anij",
            "majel",
            "majol",
            "republic of the marshall islands",
        ],
    },
    {
        iso3: "MKD",
        iso2: "MK",
        m49: "807",
        name: "North Macedonia",
        aliases: [
            "🇲🇰",
            "former yugoslav republic of macedonia",
            "fyr macedonia",
            "fyrom",
            "irjm",
            "ish republika jugosllave e maqedonise",
            "macedonia",
            "maqedoni",
            "maqedonia",
            "maqedonia e veriut",
            "republic of macedonia",
            "republic of north macedonia",
            "republika e maqedonise",
            "republika e maqedonise se veriut",
            "македонија",
            "република македонија",
            "република северна македонија",
            "рм",
            "рсм",
            "северна македонија",
        ],
    },
    {
        iso3: "MLI",
        iso2: "ML",
        m49: "466",
        name: "Mali",
        aliases: ["🇲🇱", "maali", "republic of mali"],
    },
    {
        iso3: "MLT",
        iso2: "MT",
        m49: "470",
        name: "Malta",
        aliases: ["🇲🇹", "malta island", "repubblika ta malta", "republic of malta"],
    },
    {
        iso3: "MMR",
        iso2: "MM",
        m49: "104",
        name: "Myanmar",
        aliases: [
            "🇲🇲",
            "burma",
            "pyidaungzu myanma naingngandaw",
            "pyidaungzu thammada myanma naingngandaw",
            "republic of the union of myanmar",
            "union of burma",
            "ပြည်ထောင်စု မြန်မာနိုင်ငံ",
            "ပြည်ထောင်စု မြန်မာနိုင်ငံတော်",
            "ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံ",
            "ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်",
            "ပြည်ထောင်စုမြန်မာနိုင်ငံတော်",
            "ပြည်ထောင်စုသမ္မတမြန်မာနိုင်ငံ",
            "ပြ‌ည်ထောင်စုသမ္မတမြန်မာနိုင်ငံ",
            "ပြည်ထောင်စုသမ္မတမြန်မာနိုင်ငံတော်",
            "ဗမာပြည်",
            "မြန်မာ",
            "မြန်မာနိုင်ငံ",
            "မြန်မာနိုင်ငံတော်",
            "မြန်မာပြည်",
        ],
    },
    {
        iso3: "MNE",
        iso2: "ME",
        m49: "499",
        name: "Montenegro",
        aliases: ["🇲🇪", "crna cora", "црна гора"],
    },
    {
        iso3: "MNG",
        iso2: "MN",
        m49: "496",
        name: "Mongolia",
        aliases: [
            "🇲🇳",
            "bugd nayramdah mongol ard uls",
            "mongol uls",
            "state of mongolia",
            "монгол",
            "монгол улс",
            "ᠮᠤᠩᠭᠤᠯ ᠤᠯᠤᠰ",
        ],
    },
    {
        iso3: "MNP",
        iso2: "MP",
        m49: "580",
        name: "Northern Mariana Islands",
        aliases: [
            "🇲🇵",
            "cnmi",
            "commonwealth of the northern maria islands",
            "commonwealth of the northern mariana islands",
            "northern marianas",
            "notte marianas",
            "sankattan siha na islas marianas",
        ],
    },
    {
        iso3: "MOZ",
        iso2: "MZ",
        m49: "508",
        name: "Mozambique",
        aliases: ["🇲🇿", "mocambique", "republic of mozambique", "republica de mocambique"],
    },
    {
        iso3: "MRT",
        iso2: "MR",
        m49: "478",
        name: "Mauritania",
        aliases: ["🇲🇷", "islamic republic of mauritania", "الجمهورية الإسلامية الموريتانية", "موريتانيا"],
    },
    {
        iso3: "MSR",
        iso2: "MS",
        m49: "500",
        name: "Montserrat",
        aliases: ["🇲🇸", "island of montserrat"],
    },
    {
        iso3: "MTQ",
        iso2: "MQ",
        m49: "474",
        name: "Martinique",
        aliases: ["🇲🇶", "territorial collectivity of martinique"],
    },
    {
        iso3: "MUS",
        iso2: "MU",
        m49: "480",
        name: "Mauritius",
        aliases: [
            "🇲🇺",
            "ile maurice",
            "la republique de maurice",
            "maurice",
            "moris",
            "republic of mauritius",
            "republique de maurice",
        ],
    },
    {
        iso3: "MWI",
        iso2: "MW",
        m49: "454",
        name: "Malawi",
        aliases: ["🇲🇼", "republic of malawi"],
    },
    {
        iso3: "MYS",
        iso2: "MY",
        m49: "458",
        name: "Malaysia",
        aliases: [
            "🇲🇾",
            "federation of malaysia",
            "malaysia federation",
            "negara seberang tambak",
            "persekutuan malaysia",
        ],
    },
    {
        iso3: "MYT",
        iso2: "YT",
        m49: "175",
        name: "Mayotte",
        aliases: ["🇾🇹", "departement de mayotte", "departement region de mayotte", "department of mayotte"],
    },
    {
        iso3: "NAM",
        iso2: "NA",
        m49: "516",
        name: "Namibia",
        aliases: ["🇳🇦", "republic of namibia"],
    },
    {
        iso3: "NCL",
        iso2: "NC",
        m49: "540",
        name: "New Caledonia",
        aliases: [
            "🇳🇨",
            "caledonie",
            "kanaky",
            "kanaky nouvelle caledonie",
            "nouvelle caledonie",
            "territoire de la nouvelle caledonie et dependances",
            "territoire des nouvelle caledonie et dependances",
            "territory of new caledonia and dependencies",
        ],
    },
    {
        iso3: "NER",
        iso2: "NE",
        m49: "562",
        name: "Niger",
        aliases: ["🇳🇪", "jamhuriyar nijar", "nijar", "republic niger", "republic of niger", "republic of the niger"],
    },
    {
        iso3: "NFK",
        iso2: "NF",
        m49: "574",
        name: "Norfolk Island",
        aliases: [
            "🇳🇫",
            "norfolk island australia",
            "norfolk island other territories",
            "norfolk island other territories australia",
            "territory of norfolk island",
        ],
    },
    {
        iso3: "NGA",
        iso2: "NG",
        m49: "566",
        name: "Nigeria",
        aliases: ["🇳🇬", "federal republic of nigeria", "naija"],
    },
    {
        iso3: "NIC",
        iso2: "NI",
        m49: "558",
        name: "Nicaragua",
        aliases: ["🇳🇮", "republic of nicaragua", "republica de nicaragua"],
    },
    {
        iso3: "NIU",
        iso2: "NU",
        m49: "570",
        name: "Niue",
        aliases: ["🇳🇺"],
    },
    {
        iso3: "NLD",
        iso2: "NL",
        m49: "528",
        name: "Kingdom of the Netherlands",
        aliases: [
            "🇳🇱",
            "hollandt",
            "kingdom of netherlands",
            "koninkrijk der nederlanden",
            "nederland",
            "nederlanden",
            "nederlandt",
            "netherlands",
        ],
    },
    {
        iso3: "NOR",
        iso2: "NO",
        m49: "578",
        name: "Norway",
        aliases: ["🇳🇴", "kingdom of norway", "kongeriket noreg", "kongeriket norge", "noreg", "norge"],
    },
    {
        iso3: "NPL",
        iso2: "NP",
        m49: "524",
        name: "Nepal",
        aliases: [
            "🇳🇵",
            "bal bo",
            "bal poi yul",
            "bal yul",
            "balbo",
            "balpo",
            "balpo yul",
            "nipal",
            "sanghiya loktantrik ganatantra nepal",
            "नेपाल",
            "संघिय लोकतान्त्रिक गणतन्त्र नेपाल",
            "संघिय लोकतान्त्रिक गणतन्त्रात्मक नेपाल",
            "संघीय लोकतान्त्रिक गणतन्त्र नेपाल",
        ],
    },
    {
        iso3: "NRU",
        iso2: "NR",
        m49: "520",
        name: "Nauru",
        aliases: ["🇳🇷", "naoero", "pleasant island", "republic of nauru"],
    },
    {
        iso3: "NZL",
        iso2: "NZ",
        m49: "554",
        name: "New Zealand",
        aliases: ["🇳🇿", "aotearoa", "aotearoa new zealand", "dominion of new zealand"],
    },
    {
        iso3: "OMN",
        iso2: "OM",
        m49: "512",
        name: "Oman",
        aliases: ["🇴🇲", "sultanate of oman", "uman", "سلطنة عمان", "عمان"],
    },
    {
        iso3: "PAK",
        iso2: "PK",
        m49: "586",
        name: "Pakistan",
        aliases: [
            "🇵🇰",
            "hoi quoc",
            "islamic republic of pakistan",
            "republic of pakistan",
            "tay hoi",
            "اسلامی جمہوریہ پاکستان",
            "باکستان",
            "پاکستان",
        ],
    },
    {
        iso3: "PAN",
        iso2: "PA",
        m49: "591",
        name: "Panama",
        aliases: ["🇵🇦", "republic of panama", "republica de panama"],
    },
    {
        iso3: "PCN",
        iso2: "PN",
        m49: "612",
        name: "Pitcairn",
        aliases: [
            "🇵🇳",
            "occas island",
            "pisskern aliеn",
            "pitcairn henderson ducie and oeno islands",
            "pitcairn island",
            "pitcairn islands",
            "pitkern ailen",
        ],
    },
    {
        iso3: "PER",
        iso2: "PE",
        m49: "604",
        name: "Peru",
        aliases: ["🇵🇪", "piruw", "piruw ripuwlika", "republic of peru", "republica del peru"],
    },
    {
        iso3: "PHL",
        iso2: "PH",
        m49: "608",
        name: "Philippines",
        aliases: ["🇵🇭", "philippine islands", "republic of the philippines"],
    },
    {
        iso3: "PLW",
        iso2: "PW",
        m49: "585",
        name: "Palau",
        aliases: [
            "🇵🇼",
            "belau",
            "peeloo",
            "pelew",
            "pelew islands",
            "pellew",
            "republic of belau",
            "republic of palau",
            "パラオ",
            "パラオ共和国",
        ],
    },
    {
        iso3: "PNG",
        iso2: "PG",
        m49: "598",
        name: "Papua New Guinea",
        aliases: ["🇵🇬", "independent state of papua new guinea", "papua niugini"],
    },
    {
        iso3: "POL",
        iso2: "PL",
        m49: "616",
        name: "Poland",
        aliases: ["🇵🇱", "polska", "republic of poland", "rzeczpospolita polska"],
    },
    {
        iso3: "PRI",
        iso2: "PR",
        m49: "630",
        name: "Puerto Rico",
        aliases: [
            "🇵🇷",
            "boriken",
            "borinquen",
            "boriquen",
            "commonwealth of puerto rico",
            "estado libre asociado de puerto rico",
            "free associated state of puerto rico",
            "isla del encanto",
            "island of enchantment",
            "isle of enchantment",
            "mancomunidad de puerto rico",
            "porto rico",
            "territorio de puerto rico",
            "territorio estadounidense de puerto rico",
            "territory of porto rico",
            "territory of puerto rico",
        ],
    },
    {
        iso3: "PRK",
        iso2: "KP",
        m49: "408",
        name: "Democratic People's Republic of Korea",
        aliases: [
            "🇰🇵",
            "choson minjujuui inmin konghwaguk",
            "dpr korea",
            "dprk",
            "n korea",
            "north korea",
            "공화국",
            "북조선",
            "북한",
            "조선",
            "조선민주주의인민공화국",
        ],
    },
    {
        iso3: "PRT",
        iso2: "PT",
        m49: "620",
        name: "Portugal",
        aliases: ["🇵🇹", "republica portuguesa"],
    },
    {
        iso3: "PRY",
        iso2: "PY",
        m49: "600",
        name: "Paraguay",
        aliases: ["🇵🇾", "paraguai", "republic of paraguay", "republica del paraguay", "teta paraguai"],
    },
    {
        iso3: "PSE",
        iso2: "PS",
        m49: "275",
        name: "State of Palestine",
        aliases: [
            "🇵🇸",
            "palestine",
            "palestinian authority",
            "palestinian national authority",
            "palestinian territory",
            "west bank and gaza",
            "أراضي فلسطينية",
            "الأراضي الفلسطينية",
            "الدولة الفلسطينية",
            "السلطة الفلسطينية",
            "السلطة الوطنية الفلسطينية",
            "الضفة الغربية وقطاع غزة",
            "دولة فلسطين",
            "فلسطين",
        ],
    },
    {
        iso3: "PYF",
        iso2: "PF",
        m49: "258",
        name: "French Polynesia",
        aliases: [
            "🇵🇫",
            "f oh",
            "french establishments in oceania",
            "french oceania",
            "french settlements in oceania",
            "polynesie francaise",
            "territoire de la polynesie francaise",
            "territory of french polynesia",
        ],
    },
    {
        iso3: "QAT",
        iso2: "QA",
        m49: "634",
        name: "Qatar",
        aliases: ["🇶🇦", "state of qatar", "إمارة قطر", "دولة قطر", "قطر"],
    },
    {
        iso3: "REU",
        iso2: "RE",
        m49: "638",
        name: "Réunion",
        aliases: ["🇷🇪", "ile bourbon", "ile de la reunion", "la reunion", "re", "region reunion", "reunion island"],
    },
    {
        iso3: "ROU",
        iso2: "RO",
        m49: "642",
        name: "Romania",
        aliases: ["🇷🇴"],
    },
    {
        iso3: "RUS",
        iso2: "RU",
        m49: "643",
        name: "Russian Federation",
        aliases: ["🇷🇺", "federation of russia", "russia", "россииская федерация", "россия", "рф"],
    },
    {
        iso3: "RWA",
        iso2: "RW",
        m49: "646",
        name: "Rwanda",
        aliases: [
            "🇷🇼",
            "igihugu cyimisozi igihumbi",
            "jamhuri ya rwanda",
            "la republique du rwanda",
            "republic of rwanda",
            "republika yu rwanda",
            "republique du rwanda",
            "republique rwandaise",
            "repubulika yu rwanda",
            "the land of a thousand hills",
            "u rwanda",
        ],
    },
    {
        iso3: "SAU",
        iso2: "SA",
        m49: "682",
        name: "Saudi Arabia",
        aliases: [
            "🇸🇦",
            "kingdom of saudi arabia",
            "الدولة السعودية",
            "الدوله السعوديه",
            "السعودية",
            "السعوديه",
            "العربية السعودية",
            "المملكة",
            "المملكة السعودية",
            "المملكة العربية",
            "المملكة العربية السعودية",
            "المملكه",
            "المملكه العربيه السعوديه",
            "بلاد الحرمين الشريفين",
            "دولة آل سعود",
            "سعودية",
            "سعوديه",
            "منبع الرسالة",
            "مهبط الوحي",
        ],
    },
    {
        iso3: "SDN",
        iso2: "SD",
        m49: "729",
        name: "Sudan",
        aliases: [
            "🇸🇩",
            "al sudan",
            "as sudan",
            "north sudan",
            "republic of sudan",
            "republic of the sudan",
            "soudan",
            "السودان",
            "جمهورية السودان",
        ],
    },
    {
        iso3: "SEN",
        iso2: "SN",
        m49: "686",
        name: "Senegal",
        aliases: ["🇸🇳", "la republique du senegal", "republic of senegal", "republique du senegal", "sen", "senegaal"],
    },
    {
        iso3: "SGP",
        iso2: "SG",
        m49: "702",
        name: "Singapore",
        aliases: [
            "🇸🇬",
            "garden city",
            "lion city",
            "republic of singapore",
            "republik singapura",
            "singapore city",
            "singapura",
            "spore",
            "சிங்கப்பூர்",
            "சிங்கப்பூர் குடியரசு",
            "சிங்கை",
            "ஸிங்கபூர்",
        ],
    },
    {
        iso3: "SGS",
        iso2: "GS",
        m49: "239",
        name: "South Georgia and the South Sandwich Islands",
        aliases: [
            "🇬🇸",
            "falkland islands dependencies",
            "sgssi",
            "south georgia",
            "south georgia & south sandwich islands",
            "south sandwich islands",
        ],
    },
    {
        iso3: "SHN",
        iso2: "SH",
        m49: "654",
        name: "Saint Helena",
        aliases: ["🇸🇭", "saint helena and dependencies", "saint helena ascension and tristan da cunha"],
    },
    {
        iso3: "SJM",
        iso2: "SJ",
        m49: "744",
        name: "Svalbard and Jan Mayen Islands",
        aliases: ["🇸🇯", "svalbard og jan mayen"],
    },
    {
        iso3: "SLB",
        iso2: "SB",
        m49: "090",
        name: "Solomon Islands",
        aliases: ["🇸🇧"],
    },
    {
        iso3: "SLE",
        iso2: "SL",
        m49: "694",
        name: "Sierra Leone",
        aliases: ["🇸🇱", "republic of sierra leone"],
    },
    {
        iso3: "SLV",
        iso2: "SV",
        m49: "222",
        name: "El Salvador",
        aliases: ["🇸🇻", "republic of el salvador", "republica de el salvador", "salvador"],
    },
    {
        iso3: "SMR",
        iso2: "SM",
        m49: "674",
        name: "San Marino",
        aliases: [
            "🇸🇲",
            "most serene republic of san marino",
            "repubblica di san marino",
            "serenissima repubblica di san marino",
        ],
    },
    {
        iso3: "SOM",
        iso2: "SO",
        m49: "706",
        name: "Somalia",
        aliases: [
            "🇸🇴",
            "as sumal",
            "federal republic of somalia",
            "jamhuuriyadda federaalka soomaaliya",
            "jamhuuriyadda soomaaliyeed",
            "soomaaliya",
            "soomaaliyeey toosoo",
            "الصومال",
            "جمهورية الصومال",
            "جمهورية الصومال الديموقراطية",
            "جمهورية الصومال الفيدرالية",
            "صومال",
        ],
    },
    {
        iso3: "SPM",
        iso2: "PM",
        m49: "666",
        name: "Saint Pierre and Miquelon",
        aliases: [
            "🇵🇲",
            "collectivite territoriale de saint pierre et miquelon",
            "saint pierre et miquelon",
            "territorial collectivity of saint pierre and miquelon",
        ],
    },
    {
        iso3: "SRB",
        iso2: "RS",
        m49: "688",
        name: "Serbia",
        aliases: ["🇷🇸", "republic of serbia", "republika srbija", "република србија", "србија"],
    },
    {
        iso3: "SSD",
        iso2: "SS",
        m49: "728",
        name: "South Sudan",
        aliases: ["🇸🇸", "republic of south sudan", "southern sudan"],
    },
    {
        iso3: "STP",
        iso2: "ST",
        m49: "678",
        name: "Sao Tome and Principe",
        aliases: [
            "🇸🇹",
            "democratic republic of sao tome and principe",
            "republica democratica de sao tome e principe",
            "sao tome e principe",
            "sao tome og principe",
        ],
    },
    {
        iso3: "SUR",
        iso2: "SR",
        m49: "740",
        name: "Suriname",
        aliases: [
            "🇸🇷",
            "dutch guiana",
            "republic of surinam",
            "republic of suriname",
            "republiek suriname",
            "surinam",
            "surrinam",
        ],
    },
    {
        iso3: "SVK",
        iso2: "SK",
        m49: "703",
        name: "Slovakia",
        aliases: ["🇸🇰", "slovak republic", "slovenska republika", "slovensko"],
    },
    {
        iso3: "SVN",
        iso2: "SI",
        m49: "705",
        name: "Slovenia",
        aliases: ["🇸🇮", "republic of slovenia", "republika slovenija", "slovenija"],
    },
    {
        iso3: "SWE",
        iso2: "SE",
        m49: "752",
        name: "Sweden",
        aliases: [
            "🇸🇪",
            "kingdom of sweden",
            "konungadomet sverige",
            "konungariket sverige",
            "kungadomet sverige",
            "kungariket sverige",
            "sverige",
            "swedish kingdom",
        ],
    },
    {
        iso3: "SWZ",
        iso2: "SZ",
        m49: "748",
        name: "Eswatini",
        aliases: ["🇸🇿", "kingdom of eswatini", "kingdom of swaziland", "swaziland", "umbuso weswatini"],
    },
    {
        iso3: "SXM",
        iso2: "SX",
        m49: "534",
        name: "Sint Maarten (Dutch part)",
        aliases: [
            "🇸🇽",
            "country of sint maarten",
            "eilandgebied sint maarten",
            "land sint maarten",
            "saint maarten",
            "saint martin dutch part",
            "sint maarten",
            "sint martin",
        ],
    },
    {
        iso3: "SYC",
        iso2: "SC",
        m49: "690",
        name: "Seychelles",
        aliases: [
            "🇸🇨",
            "la republique des seychelles",
            "repiblik sesel",
            "republic of seychelles",
            "republique des seychelles",
        ],
    },
    {
        iso3: "SYR",
        iso2: "SY",
        m49: "760",
        name: "Syrian Arab Republic",
        aliases: ["🇸🇾", "surya", "syria", "الجمهورية العربية السورية", "الشام", "سوريا", "سورية"],
    },
    {
        iso3: "TCA",
        iso2: "TC",
        m49: "796",
        name: "Turks and Caicos Islands",
        aliases: ["🇹🇨", "turks & caicos"],
    },
    {
        iso3: "TCD",
        iso2: "TD",
        m49: "148",
        name: "Chad",
        aliases: [
            "🇹🇩",
            "la republique du tchad",
            "republic of chad",
            "republique du tchad",
            "tchad",
            "تشاد",
            "جمهورية تشاد",
        ],
    },
    {
        iso3: "TGO",
        iso2: "TG",
        m49: "768",
        name: "Togo",
        aliases: ["🇹🇬", "la republique togolaise", "republique togolaise", "togolese republic"],
    },
    {
        iso3: "THA",
        iso2: "TH",
        m49: "764",
        name: "Thailand",
        aliases: [
            "🇹🇭",
            "kingdom of siam",
            "kingdom of thailand",
            "siam",
            "thai",
            "ไทย",
            "ประเทศไทย",
            "ประเทศสยาม",
            "เมืองไทย",
            "ราชอาณาจักรไทย",
            "ราชอาณาจักรสยาม",
            "สยาม",
        ],
    },
    {
        iso3: "TJK",
        iso2: "TJ",
        m49: "762",
        name: "Tajikistan",
        aliases: [
            "🇹🇯",
            "jumhurii tojikiston",
            "republic of tajikistan",
            "тоҷикистон",
            "тҷ",
            "тҷк",
            "ҷт",
            "ҷумҳурии тоҷикистон",
        ],
    },
    {
        iso3: "TKL",
        iso2: "TK",
        m49: "772",
        name: "Tokelau",
        aliases: ["🇹🇰", "tokelau islands", "union islands"],
    },
    {
        iso3: "TKM",
        iso2: "TM",
        m49: "795",
        name: "Turkmenistan",
        aliases: ["🇹🇲"],
    },
    {
        iso3: "TLS",
        iso2: "TL",
        m49: "626",
        name: "Timor-Leste",
        aliases: [
            "🇹🇱",
            "democratic republic of timor leste",
            "east timor",
            "republica democratica de timor leste",
            "republika demokratika timor lorosae",
            "timor loro sae",
            "timor lorosae",
        ],
    },
    {
        iso3: "TON",
        iso2: "TO",
        m49: "776",
        name: "Tonga",
        aliases: ["🇹🇴", "friendly islands", "kingdom of tonga", "puleanga fakatui o tonga", "tonga islands"],
    },
    {
        iso3: "TTO",
        iso2: "TT",
        m49: "780",
        name: "Trinidad and Tobago",
        aliases: ["🇹🇹", "republic of trinidad and tobago", "tobago", "trinidad"],
    },
    {
        iso3: "TUN",
        iso2: "TN",
        m49: "788",
        name: "Tunisia",
        aliases: ["🇹🇳", "republic of tunisia", "tunisian republic", "الجمهورية التونسية", "تونس", "تونس الخضراء"],
    },
    {
        iso3: "TUR",
        iso2: "TR",
        m49: "792",
        name: "Türkiye",
        aliases: ["🇹🇷", "republic of turkey", "republic of turkiye", "turkey", "turkiye cumhuriyeti"],
    },
    {
        iso3: "TUV",
        iso2: "TV",
        m49: "798",
        name: "Tuvalu",
        aliases: ["🇹🇻", "ellice islands"],
    },
    {
        iso3: "TWN",
        iso2: "TW",
        m49: "158",
        name: "Taiwan",
        aliases: [
            "🇹🇼",
            "chinese republic",
            "chinese taipei",
            "chunghwa minkuo",
            "chunghwa minkwo",
            "conghwaminku",
            "cunghwa minkwo",
            "cyukamingkok",
            "formosa",
            "nanasian",
            "nationalist china",
            "republic of china",
            "republic of china taiwan",
            "taivang",
            "taiwan province of china",
            "taiwan roc",
            "taywan",
            "taywang",
            "teywan",
            "the roc",
            "中華民國",
            "中華民國（臺灣）",
            "中華臺北",
            "台灣",
            "臺澎金馬",
            "臺灣",
        ],
    },
    {
        iso3: "TZA",
        iso2: "TZ",
        m49: "834",
        name: "United Republic of Tanzania",
        aliases: [
            "🇹🇿",
            "jamhuri ya muungano wa tanganyika na zanzibar",
            "jamhuri ya muungano wa tanzania",
            "tanzania",
            "tanzania jamhuri ya muungano wa",
            "tanzania united republic of",
            "united republic of tanganyika and zanzibar",
        ],
    },
    {
        iso3: "UGA",
        iso2: "UG",
        m49: "800",
        name: "Uganda",
        aliases: [
            "🇺🇬",
            "jamhuri ya uganda",
            "lulu ya afrika",
            "ouganda",
            "pearl of africa",
            "republic of uganda",
            "ugandah",
        ],
    },
    {
        iso3: "UKR",
        iso2: "UA",
        m49: "804",
        name: "Ukraine",
        aliases: ["🇺🇦", "ukr", "ukraina", "ukrainia", "ukrayina", "вкраіна", "украіна"],
    },
    {
        iso3: "UMI",
        iso2: "UM",
        m49: "581",
        name: "United States Minor Outlying Islands",
        aliases: ["🇺🇲", "us minor outlying islands", "us outlying islands", "usmoi"],
    },
    {
        iso3: "URY",
        iso2: "UY",
        m49: "858",
        name: "Uruguay",
        aliases: ["🇺🇾", "eastern republic of uruguay", "oriental republic of uruguay"],
    },
    {
        iso3: "USA",
        iso2: "US",
        m49: "840",
        name: "United States of America",
        aliases: [
            "🇺🇸",
            "amelika",
            "amelika hui pu ia",
            "amelika huipuia",
            "amelika mokuaina hui pu ia",
            "america",
            "eeuu",
            "eeuu de america",
            "estados unidos",
            "estados unidos de america",
            "los estados",
            "los estados unidos",
            "los estados unidos de america",
            "mokuaina hui pu ia",
            "the united states",
            "the us",
            "the us of a",
            "the us of america",
            "the usa",
            "union americana",
        ],
    },
    {
        iso3: "UZB",
        iso2: "UZ",
        m49: "860",
        name: "Uzbekistan",
        aliases: [
            "🇺🇿",
            "ozbek",
            "ozbekiston",
            "ozbekiston respublikasi",
            "republic of uzbekistan",
            "uzbekiston respublikasi",
        ],
    },
    {
        iso3: "VAT",
        iso2: "VA",
        m49: "336",
        name: "Holy See",
        aliases: [
            "🇻🇦",
            "citta del vaticano",
            "civitas vaticana",
            "colle vaticano",
            "papal state",
            "santa sede citta del vaticano",
            "state of vatican city",
            "stato della citta del vaticano",
            "status civitatis vaticanae",
            "status civitatis vaticanæ",
            "the vatican",
            "vatican city",
            "vatican city state",
            "vaticano",
        ],
    },
    {
        iso3: "VCT",
        iso2: "VC",
        m49: "670",
        name: "Saint Vincent and the Grenadines",
        aliases: ["🇻🇨", "saint vincent", "saint vincent and grenadines"],
    },
    {
        iso3: "VEN",
        iso2: "VE",
        m49: "862",
        name: "Venezuela (Bolivarian Republic of)",
        aliases: [
            "🇻🇪",
            "bolivarian republic of venezuela",
            "br venezuela",
            "estados unidos de venezuela",
            "rb venezuela",
            "republic of venezuela",
            "republica bolivariana de venezuela",
            "republica de venezuela",
            "venezuela",
        ],
    },
    {
        iso3: "VGB",
        iso2: "VG",
        m49: "092",
        name: "British Virgin Islands",
        aliases: [
            "🇻🇬",
            "bvi",
            "virgin islands british",
            "virgin islands of the united kingdom",
            "virgin islands united kingdom",
        ],
    },
    {
        iso3: "VIR",
        iso2: "VI",
        m49: "850",
        name: "United States Virgin Islands",
        aliases: [
            "🇻🇮",
            "american virgin islands",
            "us virgin islands",
            "virgin islands of the united states",
            "virgin islands us",
        ],
    },
    {
        iso3: "VNM",
        iso2: "VN",
        m49: "704",
        name: "Viet Nam",
        aliases: [
            "🇻🇳",
            "chxhcn viet nam",
            "chxhcnvn",
            "cong hoa xa hoi chu nghia viet nam",
            "socialist republic of viet nam",
            "socialist republic of vietnam",
            "vietnam",
        ],
    },
    {
        iso3: "VUT",
        iso2: "VU",
        m49: "548",
        name: "Vanuatu",
        aliases: [
            "🇻🇺",
            "la republique du vanuatu",
            "republic of vanuatu",
            "republique de vanuatu",
            "ripablik blong vanuatu",
        ],
    },
    {
        iso3: "WLF",
        iso2: "WF",
        m49: "876",
        name: "Wallis and Futuna Islands",
        aliases: [
            "🇼🇫",
            "collectivite des iles wallis et futuna",
            "emeni simete",
            "futuna",
            "iles wallis et futuna",
            "makape papilio",
            "territoire de wallis et futuna",
            "territoire des iles wallis et futuna",
            "wallis",
            "wallis & futuna",
            "wallis et futuna",
        ],
    },
    {
        iso3: "WSM",
        iso2: "WS",
        m49: "882",
        name: "Samoa",
        aliases: [
            "🇼🇸",
            "independent state of samoa",
            "malo saoloto tutoatasi o samoa",
            "samoa i sisifo",
            "western samoa",
        ],
    },
    {
        iso3: "YEM",
        iso2: "YE",
        m49: "887",
        name: "Yemen",
        aliases: ["🇾🇪", "rep yemen", "republic of yemen", "الجمهورية اليمنية", "اليمن", "دولة اليمن"],
    },
    {
        iso3: "ZAF",
        iso2: "ZA",
        m49: "710",
        name: "South Africa",
        aliases: [
            "🇿🇦",
            "aferika borwa",
            "aforika borwa",
            "afrika boroa",
            "afrika borwa",
            "afrika dzonga",
            "afurika tshipembe",
            "emzantsi afrika",
            "iningizimu afrika",
            "iriphabhulikhi ye ningizimu afrika",
            "iriphabhulikhi yeningizimu afrika",
            "iriphabhuliki yase ningizimu afrika",
            "iriphabliki yasemzantsi afrika",
            "iriphabliki yaseningizimu afrika",
            "iriphabliki yom zantsi afrika",
            "isewula afrika",
            "repabliki ya afrika borwa",
            "rephaboliki ya aforika borwa",
            "rephaboliki ya afrika borwa",
            "republic of south africa",
            "republiek van suid afrika",
            "riphabliki ra afrika dzonga",
            "rsa",
            "suid afrika",
            "umzansi",
            "umzantsi afrika",
            "unie van suid afrika",
            "union of south africa",
        ],
    },
    {
        iso3: "ZMB",
        iso2: "ZM",
        m49: "894",
        name: "Zambia",
        aliases: ["🇿🇲", "northern rhodesia", "republic of zambia"],
    },
    {
        iso3: "ZWE",
        iso2: "ZW",
        m49: "716",
        name: "Zimbabwe",
        aliases: [
            "🇿🇼",
            "ezimbabwe",
            "izimbabwe",
            "republic of zimbabwe",
            "rhodesia",
            "southern rhodesia",
            "zimbabwe rhodesia",
            "zimbagwe",
        ],
    },
];
